---
services: docker

env:
  - distro: centos7
  - distro: ubuntu1804
  - distro: ubuntu1604
  - distro: debian8
  - distro: debian9
  - distro: debian10


script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export test_idempotence=false

  # Create ssl certificate and key
  - mkdir ${PWD}/files/
  - openssl genrsa -out ${PWD}/files/tls.key 2048
  - openssl req -new -key ${PWD}/files/tls.key -out ${PWD}/files/tls.csr -subj "/C=RU/ST=NizhObl/L=NizhNov/O=RK-Tech/OU=TestUnit/CN=TestName"

  - openssl x509 -req -days 365 -in ${PWD}/files/tls.csr -signkey ${PWD}/files/tls.key -out ${PWD}/files/tls.crt

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh container_id=test1
  - ${PWD}/tests/test.sh container_id=test2 playbook=test_ssl.yml

after_failure:
  # Check what happened on systemd systems.
  - 'docker exec --tty ${container_id} env TERM=xterm systemctl -l status nginx.service'
  - 'docker exec --tty ${container_id} env TERM=xterm systemctl -l status supervisor.service'
  - 'docker exec --tty ${container_id} env TERM=xterm supervisorctl status'
  - 'docker exec --tty ${container_id} env TERM=xterm journalctl -xe --no-pager'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
