---
  - name: Add onlyoffice gpg keys
    apt_key:
      keyserver: "keyserver.ubuntu.com"
      id: "8320CA65CB2DE8E5"
      state: present
    become: yes

  - name: Add onlyoffice repositories
    apt_repository:
      repo: "{{ package_repo }}"
      state: present
    become: yes

  - name: Add debian contrib repositories
    apt_repository:
      repo: "{{ debian_repo }}"
      state: present
    when: ansible_distribution == "Debian"
    become: yes

  - name: Say 'yes' to ttf-mscorefonts-installer
    debconf:
      name: ttf-mscorefonts-installer
      question: msttcorefonts/accepted-mscorefonts-eula
      value: true
      vtype: boolean
    become: yes
    
  - name: Accept license
    debconf:
      name: "{{ package_name }}"
      question: onlyoffice/accepted-onlyoffice-license
      value: 'true'
      vtype: boolean
    become: yes
    
  - name: Install documentserver
    apt: 
      name: "{{ package_name }}"
      update_cache: yes
      state: latest
    become: yes

  - name: Configure documentserver
    template:
      src: local.json.j2
      dest: /etc/onlyoffice/documentserver/local.json
      owner: root
      group: root
      mode: 0644
    notify: restart-ds

  - name: Create db if it not exist
    shell: "{{ psql }} -f {{ createdb_sql }}"
    notify: restart-ds
