---
  - name: "Check if gpg key port is ok (port 11371)"
    wait_for:
      host: keyserver.ubuntu.com
      port: 11371
      timeout: 5
    register: gpg_port_status
    ignore_errors: true 
     
  - name: Add onlyoffice gpg keys
    apt_key:
      keyserver: "keyserver.ubuntu.com"
      id: "8320CA65CB2DE8E5"
      state: present
    become: yes
    when: not gpg_port_status.failed
    
  - name: Add onlyoffice gpg keys on port 80
    apt_key:
      keyserver: "hkp://keyserver.ubuntu.com:80"
      id: "8320CA65CB2DE8E5"
      state: present
    become: yes
    when: gpg_port_status.failed

  - name: Add onlyoffice repositories
    apt_repository:
      repo: "{{ package_repo }}"
      state: present
    become: yes

  - name: Add debian contrib repositories
    apt_repository:
      repo: "{{ debian_repo }}"
      state: present
    when: ansible_distribution == "Debian"
    become: yes

  - name: Say 'yes' to ttf-mscorefonts-installer
    debconf:
      name: ttf-mscorefonts-installer
      question: msttcorefonts/accepted-mscorefonts-eula
      value: true
      vtype: boolean
    become: yes
    
  - name: Accept license
    debconf:
      name: "{{ package_name }}"
      question: onlyoffice/accepted-onlyoffice-license
      value: 'true'
      vtype: boolean
    become: yes
    
  - name: Set up db host name
    debconf:
      name: "{{ package_name }}"
      question: onlyoffice/db-host
      value: "{{ db_server_host }}"
      vtype: string
    when: db_server_host|length > 0
    become: yes

  - name: Set up db name
    debconf:
      name: "{{ package_name }}"
      question: onlyoffice/db-name
      value: "{{ db_server_name }}"
      vtype: string
    when: db_server_name|length > 0
    become: yes

  - name: Set up db user
    debconf:
      name: "{{ package_name }}"
      question: onlyoffice/db-user
      value: "{{ db_server_user }}"
      vtype: string
    when: db_server_user|length > 0
    become: yes

  - name: Set up db user password
    debconf:
      name: "{{ package_name }}"
      question: onlyoffice/db-pwd
      value: "{{ db_server_pass }}"
      vtype: password
    when:
      - db_server_pass|length > 0
      - not ansible_check_mode
    become: yes

  - name: Install documentserver
    apt: 
      name: "{{ package_name }}"
      update_cache: yes
      state: latest
    become: yes

  - name: Set up redis host name
    shell: "{{ json }} -I -e 'this.services.CoAuthoring.redis.host  = \"{{ redis_server_host }}\"'"
    when:
      - redis_server_host|length > 0
      - is_nonfree_package|bool
    notify: restart-ds


  - name: Set up redis port number
    shell: "{{ json }} -I -e 'this.services.CoAuthoring.redis.port  = \"{{ redis_server_port }}\"'"
    when:
      - redis_server_port
      - is_nonfree_package|bool
    notify: restart-ds


  - name: Set up cluster mode
    debconf:
      name: "{{ package_name }}"
      question: onlyoffice/cluster-mode
      value: 'true'
      vtype: boolean
    become: yes
    when: cluster_mode|bool

  - name: Set up rabbitmq url
    shell: "{{ json }} -I -e 'this.rabbitmq.url = \"{{ rabbitmq_server_url }}\"'"
    when: rabbitmq_server_url|length > 0
    notify: restart-ds

  - name: Create db if it not exist
    shell: "{{ psql }} -f {{ createdb_sql }}"
    register: result
    changed_when: result.rc != 0
    notify: restart-ds

  - name: Set up JWT if needed
    become: yes
    debconf:
      name: "{{ package_name }}"
      question: onlyoffice/jwt-enabled
      value: "{{ jwt_enabled }}"
      vtype: boolean
    when: jwt_enabled|bool
    notify: restart-ds
    
  - name: Set up JWT Secret
    debconf:
      name: "{{ package_name }}"
      question: onlyoffice/jwt-secret
      value: "{{ jwt_secret }}"
      vtype: string
    when: 
      - jwt_secret|length > 0
      - jwt_enabled|bool
    become: yes

  - name: Set up JWT Header
    debconf:
      name: "{{ package_name }}"
      question: onlyoffice/jwt-header
      value: "{{ jwt_header }}"
      vtype: string
    when: 
      - jwt_header|length > 0
      - jwt_enabled|bool
    become: yes

  - name: Start example service
    supervisorctl:
      name: ds:example
      state: started
    when: start_example|bool
