- name: Include Debian variables
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Include Centos variables
  include_vars: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"

- name: Include Debian tasks
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Include Centos install tasks
  include_tasks: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"

- name: Include Centos postinstall tasks
  include_tasks: "{{ ansible_os_family }}_post.yml"
  when: ansible_os_family == "RedHat"

- name: Include SSL if needed
  include_tasks: ssl.yml
  when:  proto == "https"

- name: Supply license file
  copy:
    content: "{{ onlyoffice_license }}"
    dest: /var/www/onlyoffice/Data/license.lic
    owner: root
    group: root
    mode: 0644
  when: onlyoffice_license is defined
