- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  
- name: Include OS-specific task.
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Include nginx tasks
  include_tasks: "nginx.yml"
  tags: nginx
