- name: Include Debian variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Include Centos variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"

- name: Include Debian tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Include Centos install tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"

- name: Include Centos postinstall tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}_post.yml"
  when: ansible_os_family == "RedHat"

- name: Include SSL if needed
  ansible.builtin.include_tasks: ssl.yml
  when:  proto == "https"

- name: Include virtual path proxy
  ansible.builtin.include_tasks: proxy.yml
  when: ds_proxy_enabled | bool

- name: Supply license file
  ansible.builtin.template:
    content: "{{ onlyoffice_license }}"
    dest: /var/www/onlyoffice/Data/license.lic
    owner: root
    group: root
    mode: 0644
  when: onlyoffice_license is defined
