- name: Include Debian variables
  include_vars: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: Include Centos 7 variables
  include_vars: "RedHat.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Include Centos 8 variables
  include_vars: "RedHat8.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Include Debian tasks
  include_tasks: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: Include Centos 7 tasks
  include_tasks: "RedHat.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Include Centos 8 tasks
  include_tasks: "RedHat8.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Include SSL if needed
  include_tasks: ssl.yml
  when:  enable_ssl  == true

- name: Supply license file
  copy:
    content: "{{ onlyoffice_license }}"
    dest: /var/www/onlyoffice/Data/license.lic
    owner: root
    group: root
    mode: 0644
  when: onlyoffice_license is defined
