- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  
- name: Include OS-specific task.
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Include SSL if needed
  include_tasks: ssl.yml
  when:  enable_ssl  == true
