---
- name: Add required gpg keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "{{ epel_gpg_key }}"
    - "{{ onlyoffice_gpg_key }}"
    - "{{ nginx_gpg_key }}"

- name: Install xorg-x11-server-Xvfb
  ansible.builtin.yum:
    name: xorg-x11-server-Xvfb
    enablerepo: "rhel-7-server-rhui-optional-rpms"
    state: present
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: Install required items
  ansible.builtin.yum:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: "{{ epel_release if ansible_distribution == 'RedHat' else 'epel-release' }}"}
    - { name: "{{ onlyoffice_repo }}" }
    - { name: "{{ nginx_package }}" }

- name: Set ds port (if configured)
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: export DS_PORT={{ ds_port }}
  when:
    - ds_port

- name: Install documentserver from repo
  ansible.builtin.yum:
    name: "{{ package_name }}"
    update_cache: true
    state: "{{ package_state }}"
  when: package_url | length == 0

- name: Install the documentserver by URL
  ansible.builtin.yum:
    name: "{{ package_url }}"
    state: present
    validate_certs: true
    disable_gpg_check: true
  when: package_url | length > 0

- name: Initialize onlyoffice-documentserver (non free package)
  ansible.builtin.shell: |
    set -o pipefail
    echo -e "{{ db_server_host }}\n{{ db_server_name }}\n{{ db_server_user }}\n{{ db_server_pass }}\n{{ redis_server_host }}\n{{ rabbitmq_server_host }}\n{{ rabbitmq_server_user }}\n{{ rabbitmq_server_pass }}" | bash documentserver-configure.sh
  environment:
    CLUSTER_MODE: "{{ cluster_mode }}"
    JWT_ENABLED: "{{ jwt_enabled }}"
    JWT_SECRET: "{{ jwt_secret }}"
    JWT_HEADER: "{{ jwt_header }}"
  when: is_nonfree_package | bool

- name: Initialize onlyoffice-documentserver (free package)
  ansible.builtin.shell: |
    set -o pipefail
    echo -e "{{ db_server_host }}\n{{ db_server_name }}\n{{ db_server_user }}\n{{ db_server_pass }}\n{{ rabbitmq_server_host }}\n{{ rabbitmq_server_user }}\n{{ rabbitmq_server_pass }}" | bash documentserver-configure.sh
  environment:
    CLUSTER_MODE: "{{ cluster_mode }}"
    JWT_ENABLED: "{{ jwt_enabled }}"
    JWT_SECRET: "{{ jwt_secret }}"
    JWT_HEADER: "{{ jwt_header }}"
  when: not is_nonfree_package | bool

- name: Start example service
  ansible.builtin.systemd:
    name: ds-example
    state: started
  when: start_example | bool
