---
  - name: Add onlyoffice repo
    ansible.builtin.dnf:
      name: "{{ onlyoffice_repo }}"
      disable_gpg_check: yes
    become: yes

  - name: Install epel repo
    ansible.builtin.dnf: 
      name: epel-release
    become: yes

  - name: Install dependency
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      disable_gpg_check: yes
    with_items:
      - { name: "{{ nginx_repo }}", state: present }
    become: yes

  - name: Install documentserver from repo
    ansible.builtin.dnf:
      name: "{{ package_name }}"
      update_cache: yes
      state: latest
    become: yes
    when: package_url | lenght == 0

  - name: Install the Documentserver from URL
    ansible.builtin.dnf:
      name: "{{ package_url }}"
      state: present
      validate_certs: yes
      disable_gpg_check: yes
    when: package_url | lenght > 0
