---
- name: Add required gpg keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "{{ epel_gpg_key }}"
    - "{{ onlyoffice_gpg_key }}"

- name: Install required items
  ansible.builtin.yum:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: "{{ epel_release if ansible_distribution == 'RedHat' else 'epel-release' }}"}
    - { name: "{{ onlyoffice_repo }}" }
    - { name: "{{ nginx_package }}" }

- name: Set ds port (if configured)
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: export DS_PORT={{ ds_port }}
  when:
    - ds_port

- name: Install documentserver from repo
  ansible.builtin.yum:
    name: "{{ package_name }}"
    update_cache: true
    state: "{{ package_state }}"

- name: Install the documentserver by URL
  ansible.builtin.yum:
    name: "{{ package_url }}"
    state: present
    validate_certs: true
    disable_gpg_check: true
  when: package_url | length > 0
