---
  - name: Initialize onlyoffice-documentserver
    shell: |
      set -o pipefail
      echo -e "{{ db_server_host }}\n{{ db_server_name }}\n{{ db_server_user }}\n{{ db_server_pass }}\n{{ rabbitmq_server_host }}\n{{ rabbitmq_server_user }}\n{{ rabbitmq_server_pass }}" | bash documentserver-configure.sh \
      || echo -e "{{ db_server_host }}\n{{ db_server_name }}\n{{ db_server_user }}\n{{ db_server_pass }}\n{{ redis_server_host }}\n{{ rabbitmq_server_host }}\n{{ rabbitmq_server_user }}\n{{ rabbitmq_server_pass }}" | bash documentserver-configure.sh \
    become: yes
    environment:
      CLUSTER_MODE: "{{ cluster_mode }}"
      JWT_ENABLED: "{{ jwt_enabled }}"
      JWT_SECRET: "{{ jwt_secret }}"
      JWT_HEADER: "{{ jwt_header }}"
    when: package_name

  - name: Start example service
    supervisorctl:
      name: ds:example
      state: started
    when: start_example|bool
