---
  - name: Add onlyoffice repo
    ansible.builtin.dnf:
      name: "{{ onlyoffice_repo }}"
      disable_gpg_check: yes
    become: yes

  - name: Install epel repo
    ansible.builtin.dnf:
      name: epel-release
    become: yes

  - name: Install dependency
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      disable_gpg_check: yes
    with_items:
      - { name: "{{ nginx_repo }}", state: present }
    become: yes

  - name: Install documentserver
    ansible.builtin.dnf:
      name: "{{ package_name }}"
      update_cache: yes
      state: latest
    become: yes
