---
  - name: Add onlyoffice repo
    ansible.builtin.yum:
      name: "{{ onlyoffice_repo }}"
    become: yes

  - name: Install epel repo
    ansible.builtin.yum: 
      name: epel-release
    become: yes

  - name: Install dependency
    ansible.builtin.yum:
      name: "{{ item.name }}"
    with_items:
      - { name: "{{ msttcore_fonts }}", state: present }
      - { name: "{{ nginx_repo }}", state: present }
    become: yes

  - name: Install documentserver from repo
    ansible.builtin.yum:
      name: "{{ package_name }}"
      update_cache: yes
      state: latest
    become: yes
    when: package_url is undefined

  - name: Install the Documentserver from URL
    ansible.builtin.yum:
      name: "{{ package_url }}"
      state: present
      validate_certs: yes
    when: package_url is defined
