---
  - name: Add onlyoffice repo
    dnf:
      name: "{{ onlyoffice_repo }}"
      disable_gpg_check: yes
    become: yes

  - name: Install epel repo
    dnf: 
      name: epel-release
    become: yes

  - name: Install dependency
    dnf:
      name: "{{ item.name }}"
      disable_gpg_check: yes
    with_items:
      - { name: "{{ nginx_repo }}", state: present }
    become: yes

  - name: Install documentserver
    dnf:
      name: "{{ package_name }}"
      update_cache: yes
      state: latest
    become: yes

  - name: Initialize onlyoffice-documentserver (non free package)
    shell: echo -e "{{ db_server_host }}\n{{ db_server_name }}\n{{ db_server_user }}\n{{ db_server_pass }}\n{{ redis_server_host }}\n{{ rabbitmq_server_host }}\n{{ rabbitmq_server_user }}\n{{ rabbitmq_server_pass }}" | bash documentserver-configure.sh
    become: yes
    environment:
      CLUSTER_MODE: "{{ cluster_mode }}"
    when: is_nonfree_package|bool

  - name: Initialize onlyoffice-documentserver (free package)
    shell: echo -e "{{ db_server_host }}\n{{ db_server_name }}\n{{ db_server_user }}\n{{ db_server_pass }}\n{{ rabbitmq_server_host }}\n{{ rabbitmq_server_user }}\n{{ rabbitmq_server_pass }}" | bash documentserver-configure.sh
    become: yes
    environment:
      CLUSTER_MODE: "{{ cluster_mode }}"
    when: not is_nonfree_package|bool
  
  - name: Start example service
    supervisorctl:
      name: ds:example
      state: started
    when: start_example|bool
