---
  - name: Create certs directory
    file:
            path: "{{ certs_directory }}"
            state: directory
    when: copy_certs == true
    become: yes


  - name: Copy key to server
    copy:
            src: "{{ key_file }}"
            dest: "{{ certs_directory + 'tls.key' }}"
            owner: root
            group: root
            mode: "0400"
    when: copy_certs == true
    become: yes

  - name: Copy certificate to server
    copy:
            src: "{{ cert_file }}"
            dest: "{{ certs_directory + 'tls.crt' }}"
            owner: root
            group: root
    when: copy_certs == true
    become: yes

  - name: Copy ds.conf template
    template: 
      src: etc/onlyoffice/documentserver/nginx/ds.conf.j2
      dest: "{{ nginx_config_path }}"
      owner: root
      group: root
    notify: 
        restart-nginx
    become: yes

 
