  - name: Restart-ds
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: restarted
    with_items:
    - 'ds-converter'
    - 'ds-docservice'
    become: yes

  - name: Restart-nginx
    ansible.builtin.service:
      name: "nginx"
      state: restarted
    become: yes
