  - name: restart-ds
    community.general.supervisorctl:
      name: "{{ item }}"
      state: restarted
    with_items:
    - 'ds:converter'
    - 'ds:docservice'
    become: yes

  - name: restart-nginx
    ansible.builtin.service:
      name: "nginx"
      state: restarted
    become: yes
