  - name: restart-ds
    supervisorctl:
      name: "{{ item }}"
      state: restarted
    with_items:
    - 'ds:converter'
    - 'ds:docservice'
    become: yes

  - name: reload-nginx
    shell: nginx -s reload
    become: yes
