---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${MOLECULE_DISTRO}-${MOLECULE_SSL_ON}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    PROTO: ${MOLECULE_PROTO:-http}
    MOLECULE_NO_LOG: false
verifier:
  name: ansible
scenario:
  test_sequence:
     - destroy
     - dependency
     - syntax
     - create
     - prepare
     - converge
     - verify
     - destroy
lint: |
  set -e
  yamllint .
  ansible-lint .
