---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Install PostgreSQL Python libraries.
      apt:
        update_cache: yes
        pkg:
          - python3-psycopg2
          - gnupg
        state: present
      when: ansible_os_family == "Debian"
      changed_when: false
      failed_when: false

    - name: Install apt-utils
      apt:
        name: apt-utils
        update_cache: yes
      when: ansible_os_family == "Debian"
      changed_when: false
      failed_when: false
