---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Install PostgreSQL Python libraries.
      apt:
        update_cache: yes
        name: "python3-psycopg2"
        state: present
      when: ansible_os_family == "Debian"
      changed_when: false
      failed_when: false    