---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Prepare block
      when: ansible_os_family == "Debian"
      block:
      - name: Install required packages
        ansible.builtin.apt:
          update_cache: true
          pkg:
            - python3-psycopg2
            - gnupg
            - apt-utils
            - apt-transport-https
            - nginx
          state: present

      - name: Restart-nginx
        ansible.builtin.service:
          name: "nginx"
          state: restarted
