---
- hosts: all
  remote_user: root
  become: true
  vars:
    proto: "{{ lookup('env', 'PROTO') }}"
  tasks:
    - name: "Get health check status on {{ proto }}://localhost/healthcheck/"
      uri:
        url: "{{ proto }}://localhost/healthcheck/"
        return_content: yes
        validate_certs: no
      register: healthcheck
      failed_when: "'true' not in healthcheck.content"
