---
name: Test
'on':
  pull_request:
  push:

defaults:
  run:
    working-directory: 'ansible-role-documentserver'

jobs:

  molecule:
    name: Molecule test on
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distro:
          - centos7
          - centos8
          - debian9
          - debian10
          - debian11
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
        proto:
          - http
          - https
        include:
          - distro: centos7
            proto: ""
            package:
          - distro: centos8
            proto: ""
            package:

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'ansible-role-documentserver'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[lint,docker] docker yamllint ansible-lint

      - name: Downgrade docker
        run: |
             sudo apt-get update
             sudo apt-get install \
                ca-certificates \
                curl \
                gnupg \
                lsb-release
             sudo mkdir -p /etc/apt/keyrings
             curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
             echo \
                  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
             sudo apt-get update
             apt-cache madison docker-ce | awk '{ print $3 }'
             export VERSION_STRING=5:19.03.9~3-0~ubuntu-focal
             sudo apt-get install docker-ce=$VERSION_STRING docker-ce-cli=$VERSION_STRING containerd.io docker-compose-plugin

      - name: Create test ssl certificate and key
        run: |
          mkdir ${PWD}/files/
          openssl genrsa -out ${PWD}/files/test.key 2048
          openssl req -new -key ${PWD}/files/test.key -out ${PWD}/files/test.csr -subj "/C=RU/ST=NizhObl/L=NizhNov/O=RK-Tech/OU=TestUnit/CN=TestName"
          openssl x509 -req -days 365 -in ${PWD}/files/test.csr -signkey ${PWD}/files/test.key -out ${PWD}/files/test.crt

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_NO_LOG: 'false'
          MOLECULE_PACKAGE: ${{ matrix.package }}
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PROTO: ${{ matrix.proto}}
